theme: jekyll-theme-slate

title: Ron Belmont
email: belmonrj[at]gmail[dot]com
description: >- # this means to ignore newlines until "baseurl:"
  High energy nuclear physicist
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ronbelmont
github_username:  belmonrj

show_downloads: false
github.is_project_page: true
