theme: jekyll-theme-slate


title: Ron Belmont
description:  High energy nuclear physicist


baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


twitter_username: ronbelmont
email: belmonrj[at]gmail[dot]com


plugins:
  - "jekyll-github-metadata"


github:
  is_project_page: true


show_github_button: true


